### ISSUE TITLE
Purpose of this extension

### ISSUE THREAD

**Issue by davidanthoff** [0h7z/vscode-julia-format#1]
Quick question: what is the idea behind this package? JuliaFormatter.jl is already used and part of the main Julia extension https://marketplace.visualstudio.com/items?itemName=julialang.language-julia. If there are features missing there, wouldn't it make more sense to try to incorporate these things into the main Julia extension?

**Comment by Heptazhou** [comment]
No purpose. This is just a modified version of [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter) for personal use.
At least for now, julia-vscode has no way to set formatting options, and it seems to me that this is the simplest way to do the job.

**Comment by davidanthoff** [comment]
Ah, I see. The reason singularitti removed their extension from the marketplace was that we agreed that having a specific "Julia Formatter" extension in the marketplace could be really confusing for end-users, as they might get the impression that they need that extension in addition to the regular Julia extension if they want formatting, and then they might end up installing both and that will not lead to a better user experience. So, I guess I'm a bit worried that we might be back to that situation with a new "Julia Formatter" extension in the marketplace :) Obviously you are free to keep it there, but maybe it would make more sense to just try to make the main Julia extension do whatever you are missing, and then not have separate "Julia Formatter" extension in the marketplace? Or, if this is really just for your personal use, maybe not have it in the marketplace? Please don't take this as a negative feedback on your work here, really much more an attempt to lure you into helping out with the main Julia extension!

> At least for now, julia-vscode has no way to set formatting options, and it seems to me that this is the simplest way to do the job.

The extension fully supports the regular configuration of formatting settings via a `.JuliaFormatter.toml` file. The decision to _not_ have a global (non workspace) configuration option is a conscious one at the moment, but do chime in over at https://github.com/julia-vscode/julia-vscode/issues/2762.

**Comment by Heptazhou** [comment]
I see your point. I will try to contribute to julia-vscode when I have enough time and energy. :)
Regarding your worries, no offense, but I think it is quite easy for people to realize if they have more than one formatter and it is trivial to have multiple formatters.

> ![image](https://user-images.githubusercontent.com/42952940/195990786-eedf753a-3ada-4be9-8fa8-e9746d053894.png)

Anyway, a vscode configuration, which is decided *not to have* in julia-vscode, is exactly what I want most.
And btw, as far as I know, the `.JuliaFormatter.toml` file is not well-supported by julia-vscode since it only works within workspaces (julia-vscode/julia-vscode#2589).
