### ISSUE TITLE
formatting struct 

### ISSUE THREAD

**Issue by eladfisher** [0h7z/vscode-julia-format#2]
hi, while I try to format the following code the formatter crashed because the code is in mid writing so, it lack the "end" statement.

the code I tried to format:

struct antenna
    x :: Int32
    y :: Int32
    ID :: Int32

**Comment by Heptazhou** [comment]
Hi, what is the error message?

**Comment by eladfisher** [comment]
ERROR: Base.Meta.ParseError("NetDef.jl:2: incomplete: `struct` at NetDef.jl:2 requires end")

**Comment by Heptazhou** [comment]
Well, then this is the expected behavior.
[JuliaFormatter.jl](https://github.com/domluna/JuliaFormatter.jl) only works for valid Julia code,
so you have to complete the block (with an `end`) before formatting.
