### ISSUE TITLE
ERROR: UndefVarError: valid_for_in_op not defined

### ISSUE THREAD

**Issue by jamartinezmoreno** [0h7z/vscode-julia-format#3]
Today, when starting VS code and connecting to a Host, I get the following error: ERROR: UndefVarError: valid_for_in_op not defined referring to the package Julia Formatter.

I am connecting from Mac Ventura 13.4.1 to a Linux VM. I have tried connecting with different VMs with distinct Linux distros, and the problem is the same.

It never happened to me before when doing the same steps.

Thanks for your support on this matter!

**Comment by Heptazhou** [comment]
Hi, thanks for reporting this, please share more information to help address the issue.
What version of this extension and what version of JuliaFormatter are u using?

Extension version can be seen in VSC.
For JuliaFormatter version, try running:
```sh
julia -e 'using Pkg; Pkg.status("JuliaFormatter")'
```

**Comment by jamartinezmoreno** [comment]
Hi thanks for the quick response.

The JuliaFormatter version is: JuliaFormatter v0.13.7

**Comment by Heptazhou** [comment]
Well that is really old, latest JuliaFormatter is at v1.0.35.

I have released v1.2.1, please try and see if it works.

**Comment by jamartinezmoreno** [comment]
Thanks!
