### ISSUE TITLE
Bug: Prompts me to install "JuliaFormatter" each time I reopen Vscode

### ISSUE THREAD

**Issue by xuestrange** [0h7z/vscode-julia-format#4]
Each time I reopen the vscode, the extension prompts me to install "JuliaFormatter" package. It seems a bug as I already installed JuliaFormatter.jl, and code-formatting works well in my last editing.
![image](https://github.com/0h7z/vscode-julia-format/assets/59390321/6fc85ac5-78c7-4acc-903b-6d6d17d181a3)

**Comment by Heptazhou** [comment]
Hi, thanks for reporting.

What is the output of
```sh
julia -e 'using Pkg; Pkg.status("JuliaFormatter")'
```
on your machine?

**Comment by xuestrange** [comment]
> Hi, thanks for reporting.
> 
> What is the output of
> 
> ```shell
> julia -e 'using Pkg; Pkg.status("JuliaFormatter")'
> ```
> 
> on your machine?

![image](https://github.com/0h7z/vscode-julia-format/assets/59390321/b6177fbe-3e66-43b9-998b-665ed8477e53)

**Comment by Heptazhou** [comment]
Well, CMD is not good for common use.

Anyway, run this instead then:
```sh
julia -e "using Pkg; Pkg.status(string(:JuliaFormatter))"
```
which works with both CMD and powershell.

**Comment by xuestrange** [comment]
@Heptazhou Here u are.
![image](https://github.com/0h7z/vscode-julia-format/assets/59390321/56e1cfa7-2445-49f3-91b1-ae67730b05ed)

**Comment by Heptazhou** [comment]
Alright, now the problem is clear: you have some package(s) blocking the update (do `pkg> status -o -m` if you have interest to see what it is).

I will find a way to solve this later.

**Comment by xuestrange** [comment]
Thanks. Will update to solve it temporarily
