### ISSUE TITLE
Acknowledgment Inquiry for singularitti/vscode-julia-formatter?

### ISSUE THREAD

**Issue by singularitti** [0h7z/vscode-julia-format#5]
Hi! Kudos on your work with `vscode-julia-format`!

I noticed some parallels with my earlier project, [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter), and it seems like it may have influenced your code. Great to see you make this code afloat! I was wondering if you could acknowledge my repo in your project, as a nod to the foundational work it provided. Maybe somewhere in README.md or in the code? I have acknowledged the original code my work was based on, and [mentioned yours in my repo](https://github.com/singularitti/vscode-julia-formatter/blob/master/README.md).

I appreciate your consideration of this request and look forward to your response. Regardless, best of luck with your ongoing development!

Thanks!

**Comment by Heptazhou** [comment]
Hi! This is a bit interesting.

**Comment by Heptazhou** [comment]
> I noticed some parallels with my earlier project, [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter), and it seems like it may have influenced your code.

I do not know if I get what you mean by `parallels` or `influenced`.

Obviously, this project started from (or say, is based on) cc61599838e4608207a1d4b73c763b98f1dd826e, the very last commit of the upstream (i.e., your repo [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter)), as anyone can clearly see from the commit history.

**Comment by Heptazhou** [comment]
> I was wondering if you could acknowledge my repo in your project, as a nod to the foundational work it provided. Maybe somewhere in README.md or in the code?

If you want to somehow emphasize your effort/contribution to this repo, I suggest you open a pr, as I feel no motivation to write any kind of documentation, including the README.

No doubt having no documentation is bad, but I created this project only because I would have had nothing to use otherwise.

**Comment by Heptazhou** [comment]
> I have acknowledged the original code my work was based on, and [mentioned yours in my repo](https://github.com/singularitti/vscode-julia-formatter/blob/master/README.md).

Btw, I am not sure if this is a good argument. I do not really understand the intention, but it seems you just unarchived your repo, [changed the README](https://github.com/singularitti/vscode-julia-formatter/commits/master/README.md), and archived the repo again. :)

**Comment by singularitti** [comment]
> as anyone can clearly see from the commit history.

Let's be candid. It's not very common for people to delve into the commit history. The list of contributors is somewhat concealed [here](https://github.com/0h7z/vscode-julia-format/graphs/contributors). Additionally, unlike the [previous repository](https://github.com/Heptazhou/vscode-julia-formatter), this one doesn't indicate its origin.

> I suggest you open a pr

I'd be more than willing to contribute, and I could even draft some documentation for you. However, my recent schedule has been quite hectic, so I'm planning to do this a bit later.

> but it seems you just unarchived your repo...

Indeed, I was merely making a simple request. No need for any gratitude or acknowledgment. You could consider stating, "This repository is developed as a continuation of [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter)" or "This repository serves as the successor to [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter)," among other options. It would be highly appreciated if you could acknowledge the previous contributions. The choice of phrasing is entirely up to you.

**Comment by Heptazhou** [comment]
> It's not very common for people to delve into the commit history.

I am afraid I have to disagree, but never mind, this does not matter.

> "This repository is developed as a continuation of [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter)" or "This repository serves as the successor to [singularitti/vscode-julia-formatter](https://github.com/singularitti/vscode-julia-formatter),"

Those are totally fine for me. Again, pr are welcome, whenever you have time.

**Comment by singularitti** [comment]
Thank you for your understanding! I'm happy to assist once I've completed my ongoing tasks.

> It's not very common for people to delve into the commit history.

Please pardon my phrasing, I intended to convey that it's unusual for people, especially non-technical users, to delve deep into the commit history to identify contributors, particularly in projects with a long commit history. Nevertheless, we can respectfully hold differing viewpoints on this matter.
