### ISSUE TITLE
Julia editor keeps crushing for some reason. 

### ISSUE THREAD

**Issue by SeivenBell** [0h7z/vscode-julia-format#9]
Unknown Error: Could not format code. Full error: Returned: exit code 1 fatal: error thrown and no exception handler available. ReadOnlyMemoryError() reset_page at

**Comment by Heptazhou** [comment]
Hi, a `ReadOnlyMemoryError` is likely caused by OOM.

Please run this command and paste the output here first.
```shell
julia -e 'using InteractiveUtils, Pkg; versioninfo(); Pkg.status("JuliaFormatter")'
```

**Comment by Heptazhou** [comment]
Irrelevant.
